### ISSUE TITLE
Encoding Problem in Auto-Generated jsons

### ISSUE THREAD

**Issue by enisn** [jsakamoto/Toolbelt.Blazor.I18nText#5] opened 2019-08-07 18:44 UTC
Hi,

I've just created a test project to understanding logic, I've seen an encoding problem in auto generated jsons.

- My original file here:
![image](https://user-images.githubusercontent.com/23705418/62648784-29bea300-b95c-11e9-89d3-23bc0dfe4185.png)

- Project result after run:
![image](https://user-images.githubusercontent.com/23705418/62648831-3cd17300-b95c-11e9-98dd-5a37a8e1fecb.png)

- And Auto generated json in **wwwroot**:
![image](https://user-images.githubusercontent.com/23705418/62648877-54106080-b95c-11e9-80eb-df5ccb203528.png)

I've checked encoding of files, they're **UTF-8**. There no problem after they saved. 
I think a problem occurs at runtime conversion while generating these files.

**Comment by jsakamoto** [comment] 2019-08-07 21:38
Thank you for your report!

Could you attach the zip file of archived your project to this thread?

**Comment by enisn** [comment] 2019-08-09 06:44
@jsakamoto 
Problem doesn't occur at v4.0.0,
I've just updated my version from `3.0.0.7` to `4.0.0`.

Problem doesn't occurs at 4.0.0

**Comment by valerii-sovytskyi** [comment] 2020-03-10 08:11
@jsakamoto Hello,
I have the same issue but in all the latest versions.
You can try to set this work "Привіт" into your JSON, and check if it encodes correctly

(I can't test version 4.0.0 if it works for me)

**Comment by jsakamoto** [comment] 2020-03-10 09:53
@valerii-sovytskyi 

It looks likes works fine for me, based on "Toolbelt.Blazor.I18nText" ver.7.1.0.

![image](https://user-images.githubusercontent.com/95908/76299863-20852280-62ff-11ea-8050-064d0b15ae49.png)

The localized text source file is here.

[Text.uk.zip](https://github.com/jsakamoto/Toolbelt.Blazor.I18nText/files/4311517/Text.uk.zip)

**Comment by valerii-sovytskyi** [comment] 2020-03-10 10:29
![image](https://user-images.githubusercontent.com/17310375/76303212-0a10a400-62ca-11ea-9659-723cf66d7ac9.png)
I cleaned all bin and obj folders, static JSON content in www, but still, it generates me in the wrong way.
Is there any configuration I misted that influences this generation process?

**Comment by jsakamoto** [comment] 2020-03-10 11:29
@valerii-sovytskyi 

I couldn't understand why are there some JSON files like localized source text under the "wwwroot" folder in your screenshot.

The latest version of "Toolbelt.Blazor.I18nText" doesn't output any files into the "wwwroot" folder.  
It also doesn't request any files in the "wwwroot" folder.

![fig](https://camo.githubusercontent.com/7c6c8e42fa2bf56ab8b4c59c49eda664fb9bcbbf/68747470733a2f2f6a2e6d702f326b74757a356d)

Could you provide your minimal source codes as a zip archived file that can reproduce the problem?

**Comment by valerii-sovytskyi** [comment] 2020-03-13 12:05
Hello @jsakamoto,
I have created a new templated web assembly project, added NuGet and two JSON files due to [Quick Start](https://github.com/jsakamoto/Toolbelt.Blazor.I18nText#step3---build-the-project-whenever-localized-text-source-files-are-created-or-updated) and in results, I have the same issue on [Step 3](https://github.com/jsakamoto/Toolbelt.Blazor.I18nText#step3---build-the-project-whenever-localized-text-source-files-are-created-or-updated) 

![image](https://user-images.githubusercontent.com/17310375/76618476-4f82da80-6531-11ea-8d86-17818670e475.png)

Here is an example 
[EncodingIssueReproProj.zip](https://github.com/jsakamoto/Toolbelt.Blazor.I18nText/files/4329356/EncodingIssueReproProj.zip)

**Comment by valerii-sovytskyi** [comment] 2020-03-13 12:08
> wwwroot 
I think files in wwwroot is because I tested `v.4.0.0` as @enisn sad it helped him, but not to me, so do not pay attention to this

**Comment by valerii-sovytskyi** [comment] 2020-05-02 21:04
Hi @jsakamoto. Finally, I found a solution to the current issue with a bad generation of JSON files. I figure out that my JSON file was generated not with **UTF-8 encoding**, so I saved as **UTF-8** and it helped me
So we can close the issue. I also created a pull request to change the readme file.

**Comment by jsakamoto** [comment] 2020-05-03 01:20
@valerii-sovytskyi Thank you for informed me!

I merged the PR from you just now. :)

**Closed by jsakamoto** 2020-05-03 01:20 UTC
